#!/bin/bash

D=$(cd `dirname $0` && pwd)
QDIR=$D/jobs/queue
ADIR=$D/jobs/active
CDIR=$D/jobs/complete

SSH="ssh -q -x -o BatchMode=yes -o ConnectTimeout=10 -o ServerAliveInterval=3"

jobspec="$1"

if [ "x$jobspec" = "x" ]; then
    jobspec=$USER
fi

AJOBS=$(ls -1 $ADIR | grep "^$jobspec-")
ACNT=$(echo "$AJOBS" | grep . | wc -l)
if [ $ACNT -eq 0 ]; then
    AJOBS=$(ls -1 $ADIR | grep "^$jobspec")
    ACNT=$(echo "$AJOBS" | grep . | wc -l)
    if [ $ACNT -eq 0 ]; then
	AJOBS=$(ls -1 $ADIR | grep "$jobspec")
	ACNT=$(echo "$AJOBS" | grep . | wc -l)
    fi
fi

if [ $ACNT -gt 1 ]; then
    echo "Ambiguous job specification '$jobspec'. Multiple possibilities:"
    echo "$AJOBS"
    exit 1
fi


if [ $ACNT -eq 1 ]; then
    JOBID=$AJOBS
    JOBDIR=$ADIR/$JOBID

    U=$(cat $JOBDIR/user.txt)
    H=$(cat $JOBDIR/host.txt)
    
    KRB5CCNAME=$JOBDIR/ticket.krb5 $SSH -t $U@$H screen -x dq-$JOBID -p 0
    exit $?
fi


# $ACNT -lt 1

QJOBS=$(ls -1 $QDIR | grep "^$jobspec-")
QCNT=$(echo "$QJOBS" | grep . | wc -l)
if [ $QCNT -eq 0 ]; then
    QJOBS=$(ls -1 $QDIR | grep "^$jobspec")
    QCNT=$(echo "$QJOBS" | grep . | wc -l)
    if [ $QCNT -eq 0 ]; then
	QJOBS=$(ls -1 $QDIR | grep "$jobspec")
	QCNT=$(echo "$QJOBS" | grep . | wc -l)
    fi
fi

if [ $QCNT -gt 0 ]; then
    echo "Following jobs still in queue: "
    echo "$QJOBS"
    exit 1
fi


# $ACNT -lt 1 -a $QCNT -le 0

CJOBS=$(ls -1 $CDIR | grep "^$jobspec-")
CCNT=$(echo "$CJOBS" | grep . | wc -l)
if [ $CCNT -eq 0 ]; then
    CJOBS=$(ls -1 $CDIR | grep "^$jobspec")
    CCNT=$(echo "$CJOBS" | grep . | wc -l)
    if [ $CCNT -eq 0 ]; then
	CJOBS=$(ls -1 $CDIR | grep "$jobspec")
	CCNT=$(echo "$CJOBS" | grep . | wc -l)
    fi
fi

if [ $CCNT -gt 1 ]; then
    echo "Ambiguous job specification '$jobspec'. Multiple possibilities:"
    echo "$CJOBS"
    exit 1
fi

if [ $CCNT -eq 1 ]; then
    JOBID=$CJOBS
    JOBDIR=$CDIR/$JOBID

    echo "$JOBID has completed. Use 'dq-logs $jobspec' instead."
    #cat $JOBDIR/screenlog.0
    exit $?
fi

echo "Could not find matching job for '$jobspec'"
