#!/bin/bash

D=$(cd `dirname $0` && pwd)
QDIR=$D/jobs/queue
ADIR=$D/jobs/active
CDIR=$D/jobs/complete

cmd="$1"

case "x$cmd" in
    "xactive")
	AJOBS=$(ls -1 $ADIR 2>/dev/null | fgrep - | sort -nk1 -t-)
	ACNT=$(echo "$AJOBS" | grep . | wc -l)
	echo "Active jobs: $ACNT"
	for job in $AJOBS; do
	    if [ -f $ADIR/$job/start.txt ]; then
		h=$(head -1 $ADIR/$job/host.txt)
		since_str=" - (on $host since $((`date '+%s'` - `date -f $ADIR/$job/start.txt '+%s'`))s)"
	    fi
	    echo "$job$since_str"
	done

	;;
    "xqueue")
	QJOBS=$(ls -1 $QDIR 2>/dev/null | fgrep - | sort -nk1 -t-)
	QCNT=$(echo "$QJOBS" | grep . | wc -l)
	echo "Jobs in queue: $QCNT"
	for job in $QJOBS; do
	    if [ -f $QDIR/$job/queue.txt ]; then
		since_str=" - (since $((`date '+%s'` - `date -f $QDIR/$job/queue.txt '+%s'`))s)"
	    fi
	    echo "$job$since_str"
	done

	;;
    "xcomplete")
	CJOBS=$(ls -1 $CDIR 2>/dev/null | fgrep - | sort -nk1 -t-)
	CCNT=$(echo "$CJOBS" | grep . | wc -l)
	echo "Completed jobs: $CCNT"
	for job in $CJOBS; do
	    if [ -f $CDIR/$job/finish.txt -a -f $CDIR/$job/start.txt ]; then
		took_str=" - (took $((`date -f $CDIR/$job/finish.txt '+%s'` - `date -f $CDIR/$job/start.txt '+%s'`))s)"
	    fi
	    echo "$job$took_str"
	done

	;;
    x)
	QCNT=$(ls -1 $QDIR 2>/dev/null | fgrep - | wc -l)
	ACNT=$(ls -1 $ADIR 2>/dev/null | fgrep - | wc -l)
	CCNT=$(ls -1 $CDIR 2>/dev/null | fgrep - | wc -l)

	echo "Active jobs: $ACNT"
	echo "Jobs in queue: $QCNT"
	echo "Completed jobs: $CCNT"
	;;
    *)
	(
	    QJOBS=$(ls -1 $QDIR 2>/dev/null | grep "$cmd")
	    for job in $QJOBS; do
		if [ -f $QDIR/$job/queue.txt ]; then
		    since_str=" - (since $((`date '+%s'` - `date -f $QDIR/$job/queue.txt`))s)"
		fi
		echo "$job: queued$since_str"
	    done
	    AJOBS=$(ls -1 $ADIR 2>/dev/null | grep "$cmd")
	    for job in $AJOBS; do
		if [ -f $ADIR/$job/start.txt ]; then
		    since_str=" - (since $((`date '+%s'` - `date -f $QDIR/$job/start.txt`))s)"
		fi
		echo "$job: active$since_str"
	    done
	    CJOBS=$(ls -1 $CDIR 2>/dev/null | grep "$cmd")
	    for job in $CJOBS; do
		if [ -f $CDIR/$job/finish.txt -a -f $CDIR/$job/start.txt ]; then
		    took_str=" - (took $((`date -f $CDIR/$job/finish.txt '+%s'` - `date -f $CDIR/$job/start.txt '+%s'`))s)"
		fi
		echo "$job: complete$took_str"
	    done
	) | sort -nk1 -t-
	;;
esac
