#!/bin/bash

D=$(cd `dirname $0` && pwd)
QDIR=$D/jobs/queue
ADIR=$D/jobs/active
CDIR=$D/jobs/complete

SSH="ssh -q -x -o BatchMode=yes" #" -o ConnectTimeout=10 -o ServerAliveInterval=3"

jobspec="$1"

if [ "x$jobspec" = "x" ]; then
    jobspec=$USER
fi

AJOBS=$(ls -1 $ADIR | grep "^$jobspec-")
ACNT=$(echo "$AJOBS" | grep . | wc -l)
if [ $ACNT -eq 0 ]; then
    AJOBS=$(ls -1 $ADIR | grep "^$jobspec")
    ACNT=$(echo "$AJOBS" | grep . | wc -l)
    if [ $ACNT -eq 0 ]; then
	AJOBS=$(ls -1 $ADIR | grep "$jobspec")
	ACNT=$(echo "$AJOBS" | grep . | wc -l)
    fi
fi

if [ $ACNT -gt 0 ]; then
    for JOBID in $AJOBS; do
	JOBDIR=$ADIR/$JOBID

	U=$(cat $JOBDIR/user.txt)
	H=$(cat $JOBDIR/host.txt)

	echo "Killing $JOBID on $H ..."
	KRB5CCNAME=$JOBDIR/ticket.krb5 $SSH -t $U@$H screen -S dq-$JOBID -X "quit 
"
    done
    exit $?
fi

# $ACNT -lt 1
(
    echo -n "Locking..."
    flock -xn 200 || echo -n " (locked; waiting...)"
    flock -xw 10 200 || {
	echo " Timeout!"
	echo "Please inspect system with 'dq-status' 'dq-free' etc."
	exit 1
    }

    echo " locked."

    QJOBS=$(ls -1 $QDIR | grep "^$jobspec-")
    QCNT=$(echo "$QJOBS" | grep . | wc -l)
    if [ $QCNT -eq 0 ]; then
	QJOBS=$(ls -1 $QDIR | grep "^$jobspec")
	QCNT=$(echo "$QJOBS" | grep . | wc -l)
	if [ $QCNT -eq 0 ]; then
	    QJOBS=$(ls -1 $QDIR | grep "$jobspec")
	    QCNT=$(echo "$QJOBS" | grep . | wc -l)
	fi
    fi

    if [ $QCNT -gt 0 ]; then
	for JOBID in $QJOBS; do
	    JOBDIR=$QDIR/$JOBID
	    date > $JOBDIR/abort.txt

	    echo "Canceling $JOBID ..."
	    mv $JOBDIR $CDIR
	done
	exit $?
    fi

    echo "Could not find matching job for '$jobspec'"

) 200>$QDIR/.lock

