#!/bin/bash

CLUSTER_CNT=24

CLUSTER=$(hostname -s | sed 's/[0-9]//g')
D=$(cd `dirname $0` && pwd)
Hs=$(for i in `seq $CLUSTER_CNT`; do echo $CLUSTER$i; done)
SSH="ssh -q -x -o BatchMode=yes" #" -o ConnectTimeout=10 -o ServerAliveInterval=3"
function cleanup {
    echo "Cleaning up.."
    kill -INT -- 0
    sleep 0.1
    kill -KILL -- 0
    wait
}

for h in $Hs; do
    $SSH $USER@$h CPATH=$PATH:$D:$D/scripts CPWD=$PWD $D/scripts/helper-on-all "\"$@\"" &
done

trap cleanup SIGINT
trap '' SIGTERM

wait
