#!/bin/bash

D=$(cd `dirname $0` && pwd)
umask 002

JOBSCRIPT=$1

if [ ! -r $JOBSCRIPT ]; then
    echo "Cannot read $JOBSCRIPT"
    exit 1
fi

BDIR=$D/jobs/backend
QDIR=$D/jobs/queue
ADIR=$D/jobs/active
CDIR=$D/jobs/complete

echo -n "Locking..."
mkdir -p $BDIR $QDIR $ADIR $CDIR && touch $BDIR

(
    flock -xn 200 || echo -n " (waiting...)"
    flock -xw 10 200 || {
	echo " Timeout!"
	echo "Please inspect system with 'dq-status' 'dq-free' etc."
	exit 1
    }

    echo " locked."

    touch $BDIR/.jobid # refresh NFS cache
    n=$(cat $BDIR/.jobid | sed -e 's/[^0-9]//g')
    if [ "x$n" = "x" ] ; then 
	N=1
    else
	N=$(( $n + 1 ))
    fi

    JOBID=$N-$USER
    echo $N > $BDIR/.jobid

    mkdir $BDIR/$JOBID && cp $JOBSCRIPT $BDIR/$JOBID/runme.sh && chmod +x $BDIR/$JOBID/runme.sh || exit 1
    echo $PATH:$D:$D/scripts > $BDIR/$JOBID/cpath.txt
    echo $PWD > $BDIR/$JOBID/cpwd.txt
    echo $USER > $BDIR/$JOBID/user.txt
    date > $BDIR/$JOBID/queue.txt
    set | grep DQ_ | sed 's/^/export /g' > $BDIR/$JOBID/env.txt
    if [ "x$KRB5CCNAME" != "x" ]; then
	cp $(echo $KRB5CCNAME | sed 's/^[^:]*://') $BDIR/$JOBID/ticket.krb5
	chmod g+r $BDIR/$JOBID/ticket.krb5
    fi

    ln -s "../backend/$JOBID" $QDIR/$JOBID

    echo "Job ID: '$JOBID'"

) 200>$BDIR/.lock

