#!/bin/bash

D=$(cd `dirname $0` && pwd)
cd $CPWD

NESTEDLOCK=/dev/null
if [ "x$CUDA_VISIBLE_DEVICES" != "x" ]; then
    NESTEDLOCK=/dev/nvidia$CUDA_VISIBLE_DEVICES
fi

export JOBDIR=$D/jobs/active/$JOBID
export JOBID

touch $JOBDIR/lock
(
    flock -x 200
    flock -x 201

    ( flock -x 200 $D/dq-submit-cleanup $JOBID & ) &

    $JOBDIR/runme.sh
    date > $D/jobs/active/$JOBID/finish.txt
    
) 200>$JOBDIR/lock 201>$NESTEDLOCK

$D/dq-churn

