#!/bin/bash

SUPERUSERS="zxie avati"

D=$(cd `dirname $0` && pwd)
export PATH=$CPATH:$PATH
export CPWD
export CUDA_VISIBLE_DEVICES

export JOBID=$1

cd $D/jobs/$JOBID
hostname -s > host.txt

$D/screen -L -S dq-$JOBID -d -m $D/dq-submit-inner $JOBID
$D/screen -S dq-$JOBID -X colon "multiuser on ^M"
for user in $SUPERUSERS; do
    $D/screen -S dq-$JOBID -X colon "acladd $user ^M"
done
