#!/bin/bash

#SUPERUSERS="zxie avati"

D=$(cd `dirname $0` && pwd)

export CUDA_VISIBLE_DEVICES
export JOBID=$1

export KRB5CCNAME=$D/jobs/backend/$JOBID/ticket.krb5

mkdir -p $D/jobs/active
mv $D/jobs/queue/$JOBID $D/jobs/active

cd $D/jobs/active/$JOBID

hostname -s > host.txt
echo $CUDA_VISIBLE_DEVICES > gpu.txt
date > start.txt
export PATH=`cat cpath.txt`:$PATH
export CPWD=`cat cpwd.txt`
source env.txt

pagsh -c "screen -L -S dq-$JOBID -d -m $D/dq-submit-inner $JOBID"
screen -S dq-$JOBID -X screen 9
screen -S dq-$JOBID -p 9 -X stuff "dq-keeptoken
"

#$D/screen -S dq-$JOBID -X colon "multiuser on ^M"
#for user in $SUPERUSERS; do
#    $D/screen -S dq-$JOBID -X colon "acladd $user ^M"
#done
