#!/bin/bash

D=$(cd `dirname $0` && pwd)
cd $CPWD

NESTEDLOCK=/dev/null
if [ "x$CUDA_VISIBLE_DEVICES" != "x" ]; then
    NESTEDLOCK=/dev/nvidia$CUDA_VISIBLE_DEVICES
fi

function finish {
    if [ -d $D/jobs/active/$JOBID ]; then
	date > $D/jobs/active/$JOBID/finish.txt
	mv $D/jobs/active/$JOBID $D/jobs/complete
    fi
}

function cleanup {
    echo "Cleaning up.."
    finish
    kill -KILL -- 0
    wait
}

trap cleanup SIGINT
trap '' SIGTERM

export JOBDIR=$D/jobs/active/$JOBID
export JOBID
touch $JOBDIR/lock
flock -x $JOBDIR/lock flock -x $NESTEDLOCK $JOBDIR/runme.sh
finish
$D/dq-churn

