#!/bin/bash

#SUPERUSERS="zxie avati"

D=$(cd `dirname $0` && pwd)

export CUDA_VISIBLE_DEVICES
export JOBID=$1

mkdir -p $D/jobs/active
mv $D/jobs/queue/$JOBID $D/jobs/active

cd $D/jobs/active/$JOBID

hostname -s > host.txt
date > start.txt
export PATH=`cat cpath.txt`:$PATH
export CPWD=`cat cpwd.txt`
source env.txt

$D/screen -L -S dq-$JOBID -d -m $D/dq-submit-inner $JOBID
#$D/screen -S dq-$JOBID -X colon "multiuser on ^M"
#for user in $SUPERUSERS; do
#    $D/screen -S dq-$JOBID -X colon "acladd $user ^M"
#done
