#!/bin/bash

D=$(cd `dirname $0` && pwd)


$D/dq-on-all gpu-users | { while read line; do
	echo -n "."
	OUT="$OUT$line
"
    done

    echo
    (
	echo "Host GPU Mem User Process PID Status"
	echo "---- --- --- ---- ------- --- ------"
	echo "$OUT"
    ) | column -t
}
