#!/bin/bash

D=$(cd `dirname $0` && pwd)

function disp {
    echo
    (
	echo "Host GPU Mem User Process PID Status"
	echo "---- --- --- ---- ------- --- ------"
	echo "$OUT"
    ) | column -t

    exit
}

$D/dq-on-all gpu-users | {
    trap disp SIGINT

    while read line; do
	echo -n "."
	OUT="$OUT$line
"
    done

    disp "$OUT"
}
